# Generated by Django 4.0 on 2021-12-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0003_alter_vehicles_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='driver_id',
            field=models.ForeignKey(on_delete=models.SET(1), to='ParkApp.drivers'),
        ),
    ]
