# Generated by Django 4.0 on 2021-12-14 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParkApp', '0004_alter_vehicles_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ParkApp.drivers'),
        ),
    ]
